// <auto-generated />
using System;
using CourseService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseService.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20260606035927_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseService.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStudents")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClassId");

                    b.HasIndex("CourseId");

                    b.HasIndex("Status");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            ClassName = "TA-CB-01",
                            CourseId = 1,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStudents = 5,
                            EndDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxStudents = 25,
                            Room = "P.101",
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProgress",
                            TeacherId = 2,
                            TeacherName = "Nguyễn Văn An"
                        },
                        new
                        {
                            ClassId = 2,
                            ClassName = "TA-CB-02",
                            CourseId = 1,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStudents = 2,
                            EndDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxStudents = 30,
                            Room = "P.102",
                            StartDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Opened",
                            TeacherId = 3,
                            TeacherName = "Trần Thị Bình"
                        },
                        new
                        {
                            ClassId = 3,
                            ClassName = "TOEIC-01",
                            CourseId = 2,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStudents = 4,
                            EndDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxStudents = 20,
                            Room = "P.201",
                            StartDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProgress",
                            TeacherId = 2,
                            TeacherName = "Nguyễn Văn An"
                        },
                        new
                        {
                            ClassId = 4,
                            ClassName = "PY-01",
                            CourseId = 3,
                            CreatedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStudents = 3,
                            EndDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxStudents = 20,
                            Room = "P.Lab1",
                            StartDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProgress",
                            TeacherId = 4,
                            TeacherName = "Lê Văn Cường"
                        },
                        new
                        {
                            ClassId = 5,
                            ClassName = "FS-REACT-01",
                            CourseId = 8,
                            CreatedAt = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStudents = 6,
                            EndDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxStudents = 24,
                            Room = "P.Lab2",
                            StartDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProgress",
                            TeacherId = 4,
                            TeacherName = "Lê Văn Cường"
                        },
                        new
                        {
                            ClassId = 6,
                            ClassName = "KN-QLTG-01",
                            CourseId = 9,
                            CreatedAt = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStudents = 2,
                            EndDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxStudents = 40,
                            Room = "P.301",
                            StartDate = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Opened",
                            TeacherId = 8,
                            TeacherName = "Lê Thị Hoa"
                        },
                        new
                        {
                            ClassId = 7,
                            ClassName = "JP-N5-01",
                            CourseId = 10,
                            CreatedAt = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStudents = 3,
                            EndDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxStudents = 20,
                            Room = "P.103",
                            StartDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Opened",
                            TeacherId = 9,
                            TeacherName = "Phạm Văn Khánh"
                        },
                        new
                        {
                            ClassId = 8,
                            ClassName = "VUEJS-01",
                            CourseId = 11,
                            CreatedAt = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStudents = 3,
                            EndDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxStudents = 20,
                            Room = "P.Lab1",
                            StartDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProgress",
                            TeacherId = 4,
                            TeacherName = "Lê Văn Cường"
                        });
                });

            modelBuilder.Entity("CourseService.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseId");

                    b.HasIndex("Category");

                    b.HasIndex("CourseName");

                    b.HasIndex("IsActive");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Category = "NgoaiNgu",
                            CourseName = "Tiếng Anh giao tiếp cơ bản",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Khóa học tiếng Anh giao tiếp dành cho người mới bắt đầu, tập trung vào kỹ năng nghe và nói.",
                            Fee = 2500000m,
                            IsActive = true,
                            Level = "Beginner",
                            TotalSessions = 30,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourseId = 2,
                            Category = "NgoaiNgu",
                            CourseName = "TOEIC 600+",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Luyện thi TOEIC đạt 600+ điểm, bao gồm cả Listening và Reading.",
                            Fee = 3500000m,
                            IsActive = true,
                            Level = "Intermediate",
                            TotalSessions = 40,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourseId = 3,
                            Category = "TinHoc",
                            CourseName = "Lập trình Python cơ bản",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Khóa học lập trình Python cho người mới, từ cú pháp cơ bản đến xây dựng ứng dụng đơn giản.",
                            Fee = 3000000m,
                            IsActive = true,
                            Level = "Beginner",
                            TotalSessions = 24,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourseId = 4,
                            Category = "KyNang",
                            CourseName = "Kỹ năng thuyết trình",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rèn luyện kỹ năng thuyết trình chuyên nghiệp, tự tin trước đám đông.",
                            Fee = 1800000m,
                            IsActive = true,
                            Level = "Intermediate",
                            TotalSessions = 12,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourseId = 5,
                            Category = "NgoaiNgu",
                            CourseName = "IELTS 6.5+",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Luyện thi IELTS đạt band 6.5+, bao gồm 4 kỹ năng Listening, Reading, Writing, Speaking.",
                            Fee = 5000000m,
                            IsActive = true,
                            Level = "Advanced",
                            TotalSessions = 48,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourseId = 8,
                            Category = "TinHoc",
                            CourseName = "Lập trình Web với React & Node.js",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Khóa học Fullstack Web Development sử dụng React cho Frontend và Express/Node.js cho Backend.",
                            Fee = 4500000m,
                            IsActive = true,
                            Level = "Intermediate",
                            TotalSessions = 36,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourseId = 9,
                            Category = "KyNang",
                            CourseName = "Kỹ năng quản lý thời gian",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Học cách lập kế hoạch, sắp xếp công việc, và tối ưu hóa năng suất làm việc hàng ngày.",
                            Fee = 1500000m,
                            IsActive = true,
                            Level = "Beginner",
                            TotalSessions = 10,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourseId = 10,
                            Category = "NgoaiNgu",
                            CourseName = "Tiếng Nhật sơ cấp N5",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Khóa học dành cho người bắt đầu làm quen với bảng chữ cái Hiragana, Katakana và giao tiếp cơ bản.",
                            Fee = 2800000m,
                            IsActive = true,
                            Level = "Beginner",
                            TotalSessions = 32,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourseId = 11,
                            Category = "TinHoc",
                            CourseName = "Lập trình Web với Vue.js",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Khóa học phát triển giao diện Web Single Page Application hiện đại với framework Vue.js 3.",
                            Fee = 3800000m,
                            IsActive = true,
                            Level = "Intermediate",
                            TotalSessions = 24,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourseId = 12,
                            Category = "KyNang",
                            CourseName = "Kỹ năng làm việc nhóm (Teamwork)",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rèn luyện kỹ năng phối hợp, giao tiếp và giải quyết xung đột trong môi trường làm việc nhóm hiệu quả.",
                            Fee = 1200000m,
                            IsActive = true,
                            Level = "Beginner",
                            TotalSessions = 8,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CourseService.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ClassId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            ClassId = 1,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            Session = "Sang",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 2,
                            ClassId = 1,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            Session = "Sang",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 3,
                            ClassId = 1,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            Session = "Sang",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 4,
                            ClassId = 2,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            Session = "Chieu",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 5,
                            ClassId = 2,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            Session = "Chieu",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 6,
                            ClassId = 3,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 20, 30, 0, 0),
                            Session = "Toi",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 7,
                            ClassId = 3,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 20, 30, 0, 0),
                            Session = "Toi",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 8,
                            ClassId = 4,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            Session = "Sang",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 9,
                            ClassId = 4,
                            DayOfWeek = 7,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            Session = "Sang",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 10,
                            ClassId = 5,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 20, 30, 0, 0),
                            Session = "Toi",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 11,
                            ClassId = 5,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 20, 30, 0, 0),
                            Session = "Toi",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 12,
                            ClassId = 6,
                            DayOfWeek = 7,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            Session = "Sang",
                            StartTime = new TimeSpan(0, 8, 30, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 13,
                            ClassId = 7,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 16, 30, 0, 0),
                            Session = "Chieu",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 14,
                            ClassId = 7,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 16, 30, 0, 0),
                            Session = "Chieu",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 15,
                            ClassId = 8,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 20, 30, 0, 0),
                            Session = "Toi",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            ScheduleId = 16,
                            ClassId = 8,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 20, 30, 0, 0),
                            Session = "Toi",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("CourseService.Models.Class", b =>
                {
                    b.HasOne("CourseService.Models.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseService.Models.Schedule", b =>
                {
                    b.HasOne("CourseService.Models.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("CourseService.Models.Class", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CourseService.Models.Course", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
