// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentService.Data;

#nullable disable

namespace StudentService.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20260605070303_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentService.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int?>("MarkedByTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("SessionDate");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            AttendanceId = 1,
                            CreatedAt = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1,
                            MarkedByTeacherId = 2,
                            SessionDate = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "CoMat"
                        },
                        new
                        {
                            AttendanceId = 2,
                            CreatedAt = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1,
                            MarkedByTeacherId = 2,
                            SessionDate = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "CoMat"
                        },
                        new
                        {
                            AttendanceId = 3,
                            CreatedAt = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1,
                            MarkedByTeacherId = 2,
                            Note = "Trễ 10 phút",
                            SessionDate = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DiTre"
                        },
                        new
                        {
                            AttendanceId = 4,
                            CreatedAt = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 2,
                            MarkedByTeacherId = 2,
                            SessionDate = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "CoMat"
                        },
                        new
                        {
                            AttendanceId = 5,
                            CreatedAt = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 2,
                            MarkedByTeacherId = 2,
                            Note = "Không phép",
                            SessionDate = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Vang"
                        },
                        new
                        {
                            AttendanceId = 6,
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 3,
                            MarkedByTeacherId = 2,
                            SessionDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "CoMat"
                        },
                        new
                        {
                            AttendanceId = 7,
                            CreatedAt = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 3,
                            MarkedByTeacherId = 2,
                            Note = "Xin phép nghỉ",
                            SessionDate = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "CoPhep"
                        });
                });

            modelBuilder.Entity("StudentService.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId", "ClassId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            ClassId = 1,
                            EnrolledAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            ClassId = 1,
                            EnrolledAt = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 3,
                            ClassId = 3,
                            EnrolledAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 4,
                            ClassId = 4,
                            EnrolledAt = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("StudentService.Models.ExamResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("GradedByTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ResultId");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("ExamResults");

                    b.HasData(
                        new
                        {
                            ResultId = 1,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1,
                            ExamDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExamType = "KiemTra",
                            GradedByTeacherId = 2,
                            Note = "Bài kiểm tra 15 phút",
                            Score = 8.5m
                        },
                        new
                        {
                            ResultId = 2,
                            CreatedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1,
                            ExamDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExamType = "GiuaKy",
                            GradedByTeacherId = 2,
                            Note = "Kiểm tra giữa kỳ",
                            Score = 7.0m
                        },
                        new
                        {
                            ResultId = 3,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 2,
                            ExamDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExamType = "KiemTra",
                            GradedByTeacherId = 2,
                            Score = 9.0m
                        },
                        new
                        {
                            ResultId = 4,
                            CreatedAt = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 3,
                            ExamDate = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExamType = "KiemTra",
                            GradedByTeacherId = 2,
                            Note = "Cần cải thiện phần Listening",
                            Score = 6.5m
                        },
                        new
                        {
                            ResultId = 5,
                            CreatedAt = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 4,
                            ExamDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExamType = "KiemTra",
                            GradedByTeacherId = 3,
                            Note = "Xuất sắc",
                            Score = 9.5m
                        });
                });

            modelBuilder.Entity("StudentService.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("Email");

                    b.HasIndex("FullName");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Address = "123 Nguyễn Huệ, Q1, TP.HCM",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamvand@gmail.com",
                            FullName = "Phạm Văn D",
                            Gender = "Nam",
                            Phone = "0901000005",
                            UpdatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 5
                        },
                        new
                        {
                            StudentId = 2,
                            Address = "456 Lê Lợi, Q3, TP.HCM",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2001, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hoangthie@gmail.com",
                            FullName = "Hoàng Thị E",
                            Gender = "Nu",
                            Phone = "0901000006",
                            UpdatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 6
                        },
                        new
                        {
                            StudentId = 3,
                            Address = "789 Trần Hưng Đạo, Q5, TP.HCM",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1999, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuvang@gmail.com",
                            FullName = "Vũ Văn G",
                            Gender = "Nam",
                            Phone = "0901000007",
                            UpdatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 7
                        });
                });

            modelBuilder.Entity("StudentService.Models.Attendance", b =>
                {
                    b.HasOne("StudentService.Models.Enrollment", "Enrollment")
                        .WithMany("Attendances")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("StudentService.Models.Enrollment", b =>
                {
                    b.HasOne("StudentService.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentService.Models.ExamResult", b =>
                {
                    b.HasOne("StudentService.Models.Enrollment", "Enrollment")
                        .WithMany("ExamResults")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("StudentService.Models.Enrollment", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ExamResults");
                });

            modelBuilder.Entity("StudentService.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
