// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentService.Data;

#nullable disable

namespace StudentService.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentService.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int?>("MarkedByTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("SessionDate");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            AttendanceId = 1,
                            CreatedAt = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1,
                            MarkedByTeacherId = 2,
                            SessionDate = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "CoMat"
                        },
                        new
                        {
                            AttendanceId = 2,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1,
                            MarkedByTeacherId = 2,
                            SessionDate = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "CoMat"
                        },
                        new
                        {
                            AttendanceId = 3,
                            CreatedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1,
                            MarkedByTeacherId = 2,
                            Note = "Trễ 10 phút",
                            SessionDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DiTre"
                        },
                        new
                        {
                            AttendanceId = 4,
                            CreatedAt = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 2,
                            MarkedByTeacherId = 2,
                            SessionDate = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "CoMat"
                        },
                        new
                        {
                            AttendanceId = 5,
                            CreatedAt = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 2,
                            MarkedByTeacherId = 2,
                            Note = "Không phép",
                            SessionDate = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Vang"
                        },
                        new
                        {
                            AttendanceId = 6,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 3,
                            MarkedByTeacherId = 2,
                            SessionDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "CoMat"
                        },
                        new
                        {
                            AttendanceId = 7,
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 3,
                            MarkedByTeacherId = 2,
                            Note = "Xin phép nghỉ",
                            SessionDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "CoPhep"
                        });
                });

            modelBuilder.Entity("StudentService.Models.CourseQueue", b =>
                {
                    b.Property<int>("CourseQueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseQueueId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("CourseQueueId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("CourseQueues");
                });

            modelBuilder.Entity("StudentService.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId", "ClassId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            ClassId = 1,
                            EnrolledAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            ClassId = 1,
                            EnrolledAt = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 3,
                            ClassId = 1,
                            EnrolledAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 4,
                            ClassId = 1,
                            EnrolledAt = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 4
                        },
                        new
                        {
                            EnrollmentId = 5,
                            ClassId = 1,
                            EnrolledAt = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 5
                        },
                        new
                        {
                            EnrollmentId = 6,
                            ClassId = 2,
                            EnrolledAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 6
                        },
                        new
                        {
                            EnrollmentId = 7,
                            ClassId = 2,
                            EnrolledAt = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 7
                        },
                        new
                        {
                            EnrollmentId = 8,
                            ClassId = 3,
                            EnrolledAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 9,
                            ClassId = 3,
                            EnrolledAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 10,
                            ClassId = 3,
                            EnrolledAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 5
                        },
                        new
                        {
                            EnrollmentId = 11,
                            ClassId = 3,
                            EnrolledAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 8
                        },
                        new
                        {
                            EnrollmentId = 12,
                            ClassId = 4,
                            EnrolledAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 13,
                            ClassId = 4,
                            EnrolledAt = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 4
                        },
                        new
                        {
                            EnrollmentId = 14,
                            ClassId = 4,
                            EnrolledAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 6
                        },
                        new
                        {
                            EnrollmentId = 15,
                            ClassId = 5,
                            EnrolledAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 16,
                            ClassId = 5,
                            EnrolledAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 17,
                            ClassId = 5,
                            EnrolledAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 18,
                            ClassId = 5,
                            EnrolledAt = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 4
                        },
                        new
                        {
                            EnrollmentId = 19,
                            ClassId = 5,
                            EnrolledAt = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 5
                        },
                        new
                        {
                            EnrollmentId = 20,
                            ClassId = 5,
                            EnrolledAt = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 6
                        },
                        new
                        {
                            EnrollmentId = 21,
                            ClassId = 6,
                            EnrolledAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 7
                        },
                        new
                        {
                            EnrollmentId = 22,
                            ClassId = 6,
                            EnrolledAt = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 8
                        },
                        new
                        {
                            EnrollmentId = 23,
                            ClassId = 7,
                            EnrolledAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 24,
                            ClassId = 7,
                            EnrolledAt = new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 4
                        },
                        new
                        {
                            EnrollmentId = 25,
                            ClassId = 7,
                            EnrolledAt = new DateTime(2026, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 5
                        },
                        new
                        {
                            EnrollmentId = 26,
                            ClassId = 8,
                            EnrolledAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 6
                        },
                        new
                        {
                            EnrollmentId = 27,
                            ClassId = 8,
                            EnrolledAt = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 7
                        },
                        new
                        {
                            EnrollmentId = 28,
                            ClassId = 8,
                            EnrolledAt = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "DangHoc",
                            StudentId = 8
                        });
                });

            modelBuilder.Entity("StudentService.Models.ExamResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("GradedByTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ResultId");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("ExamResults");

                    b.HasData(
                        new
                        {
                            ResultId = 1,
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1,
                            ExamDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExamType = "KiemTra",
                            GradedByTeacherId = 2,
                            Note = "Bài kiểm tra 15 phút",
                            Score = 8.5m
                        },
                        new
                        {
                            ResultId = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1,
                            ExamDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExamType = "GiuaKy",
                            GradedByTeacherId = 2,
                            Note = "Kiểm tra giữa kỳ",
                            Score = 7.0m
                        },
                        new
                        {
                            ResultId = 3,
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 2,
                            ExamDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExamType = "KiemTra",
                            GradedByTeacherId = 2,
                            Score = 9.0m
                        },
                        new
                        {
                            ResultId = 4,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 3,
                            ExamDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExamType = "KiemTra",
                            GradedByTeacherId = 2,
                            Note = "Cần cải thiện phần Listening",
                            Score = 6.5m
                        },
                        new
                        {
                            ResultId = 5,
                            CreatedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 4,
                            ExamDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExamType = "KiemTra",
                            GradedByTeacherId = 2,
                            Note = "Xuất sắc",
                            Score = 9.5m
                        });
                });

            modelBuilder.Entity("StudentService.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("Email");

                    b.HasIndex("FullName");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Address = "123 Nguyễn Huệ, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamvandung@gmail.com",
                            FullName = "Phạm Văn Dũng",
                            Gender = "Nam",
                            Phone = "0901000005",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 12
                        },
                        new
                        {
                            StudentId = 2,
                            Address = "456 Lê Lợi, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2001, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hoangthimai@gmail.com",
                            FullName = "Hoàng Thị Mai",
                            Gender = "Nữ",
                            Phone = "0901000006",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 13
                        },
                        new
                        {
                            StudentId = 3,
                            Address = "789 Trần Hưng Đạo, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1999, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuvangiang@gmail.com",
                            FullName = "Vũ Văn Giang",
                            Gender = "Nam",
                            Phone = "0901000007",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 14
                        },
                        new
                        {
                            StudentId = 4,
                            Address = "101 Cách Mạng Tháng 8, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2002, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenvanminh@gmail.com",
                            FullName = "Nguyễn Văn Minh",
                            Gender = "Nam",
                            Phone = "0901000011",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 15
                        },
                        new
                        {
                            StudentId = 5,
                            Address = "202 Nguyễn Trãi, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hoangthinga@gmail.com",
                            FullName = "Hoàng Thị Nga",
                            Gender = "Nữ",
                            Phone = "0901000012",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 16
                        },
                        new
                        {
                            StudentId = 6,
                            Address = "303 Điện Biên Phủ, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2001, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuvanhai@gmail.com",
                            FullName = "Vũ Văn Hải",
                            Gender = "Nam",
                            Phone = "0901000013",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 17
                        },
                        new
                        {
                            StudentId = 7,
                            Address = "404 Võ Văn Tần, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2003, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lethiphuong@gmail.com",
                            FullName = "Lê Thị Phương",
                            Gender = "Nữ",
                            Phone = "0901000014",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 18
                        },
                        new
                        {
                            StudentId = 8,
                            Address = "505 Nguyễn Thị Minh Khai, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranquocquan@gmail.com",
                            FullName = "Trần Quốc Quân",
                            Gender = "Nam",
                            Phone = "0901000015",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 19
                        },
                        new
                        {
                            StudentId = 9,
                            Address = "923 Cách Mạng Tháng 8, Phường 2, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1999, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenhoangtien@gmail.com",
                            FullName = "Nguyễn Hoàng Tiến",
                            Gender = "Nam",
                            Phone = "0933341057",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 20
                        },
                        new
                        {
                            StudentId = 10,
                            Address = "743 Điện Biên Phủ, Phường 12, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 9, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenthiphuong@gmail.com",
                            FullName = "Nguyễn Thị Phương",
                            Gender = "Nữ",
                            Phone = "0934903402",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 21
                        },
                        new
                        {
                            StudentId = 11,
                            Address = "358 Hai Bà Trưng, Phường 3, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamphuongchi@gmail.com",
                            FullName = "Phạm Phương Chi",
                            Gender = "Nữ",
                            Phone = "0941109031",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 22
                        },
                        new
                        {
                            StudentId = 12,
                            Address = "836 Lê Duẩn, Phường 12, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2003, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranngocnhi@gmail.com",
                            FullName = "Trần Ngọc Nhi",
                            Gender = "Nữ",
                            Phone = "0917022674",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 23
                        },
                        new
                        {
                            StudentId = 13,
                            Address = "56 Điện Biên Phủ, Phường 4, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2001, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phanminhlong@gmail.com",
                            FullName = "Phan Minh Long",
                            Gender = "Nam",
                            Phone = "0947067228",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 24
                        },
                        new
                        {
                            StudentId = 14,
                            Address = "373 Nguyễn Trãi, Phường 11, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2003, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamminhkien@gmail.com",
                            FullName = "Phạm Minh Kiên",
                            Gender = "Nam",
                            Phone = "0948606962",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 25
                        },
                        new
                        {
                            StudentId = 15,
                            Address = "957 Điện Biên Phủ, Phường 12, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dangquoclong@gmail.com",
                            FullName = "Đặng Quốc Long",
                            Gender = "Nam",
                            Phone = "0933741438",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 26
                        },
                        new
                        {
                            StudentId = 16,
                            Address = "77 Nguyễn Trãi, Phường 15, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2003, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ngovietgiang@gmail.com",
                            FullName = "Ngô Việt Giang",
                            Gender = "Nam",
                            Phone = "0931538552",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 27
                        },
                        new
                        {
                            StudentId = 17,
                            Address = "772 Cách Mạng Tháng 8, Phường 9, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2002, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamphuongnhi@gmail.com",
                            FullName = "Phạm Phương Nhi",
                            Gender = "Nữ",
                            Phone = "0983396987",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 28
                        },
                        new
                        {
                            StudentId = 18,
                            Address = "58 Nam Kỳ Khởi Nghĩa, Phường 2, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dangkhanhlan@gmail.com",
                            FullName = "Đặng Khánh Lan",
                            Gender = "Nữ",
                            Phone = "0933320821",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 29
                        },
                        new
                        {
                            StudentId = 19,
                            Address = "551 Hai Bà Trưng, Phường 9, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2004, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lyhuuphuc@gmail.com",
                            FullName = "Lý Hữu Phúc",
                            Gender = "Nam",
                            Phone = "0917455324",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 30
                        },
                        new
                        {
                            StudentId = 20,
                            Address = "474 Lê Duẩn, Phường 12, Bình Thạnh, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2002, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ngothanhdat@gmail.com",
                            FullName = "Ngô Thành Đạt",
                            Gender = "Nam",
                            Phone = "0962871534",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 31
                        },
                        new
                        {
                            StudentId = 21,
                            Address = "790 Nguyễn Trãi, Phường 9, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2001, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "buithutuyet@gmail.com",
                            FullName = "Bùi Thu Tuyết",
                            Gender = "Nữ",
                            Phone = "0916007072",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 32
                        },
                        new
                        {
                            StudentId = 22,
                            Address = "69 Nguyễn Trãi, Phường 15, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2003, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dangviettuan@gmail.com",
                            FullName = "Đặng Việt Tuấn",
                            Gender = "Nam",
                            Phone = "0902876828",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 33
                        },
                        new
                        {
                            StudentId = 23,
                            Address = "281 Cách Mạng Tháng 8, Phường 14, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 9, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "trananhminh@gmail.com",
                            FullName = "Trần Anh Minh",
                            Gender = "Nam",
                            Phone = "0923154051",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 34
                        },
                        new
                        {
                            StudentId = 24,
                            Address = "472 Lê Duẩn, Phường 4, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2003, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamquynhthao@gmail.com",
                            FullName = "Phạm Quỳnh Thảo",
                            Gender = "Nữ",
                            Phone = "0947693979",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 35
                        },
                        new
                        {
                            StudentId = 25,
                            Address = "656 Lê Duẩn, Phường 4, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuvanbach@gmail.com",
                            FullName = "Vũ Văn Bách",
                            Gender = "Nam",
                            Phone = "0934694634",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 36
                        },
                        new
                        {
                            StudentId = 26,
                            Address = "145 Điện Biên Phủ, Phường 15, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuminhhuy@gmail.com",
                            FullName = "Vũ Minh Huy",
                            Gender = "Nam",
                            Phone = "0935672073",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 37
                        },
                        new
                        {
                            StudentId = 27,
                            Address = "372 Trần Hưng Đạo, Phường 7, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1999, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamphuonganh@gmail.com",
                            FullName = "Phạm Phương Anh",
                            Gender = "Nữ",
                            Phone = "0932582524",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 38
                        },
                        new
                        {
                            StudentId = 28,
                            Address = "204 Cách Mạng Tháng 8, Phường 8, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1999, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ngominhgiang@gmail.com",
                            FullName = "Ngô Minh Giang",
                            Gender = "Nam",
                            Phone = "0976692553",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 39
                        },
                        new
                        {
                            StudentId = 29,
                            Address = "61 Điện Biên Phủ, Phường 9, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 9, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lekimhoa@gmail.com",
                            FullName = "Lê Kim Hoa",
                            Gender = "Nữ",
                            Phone = "0932264748",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 40
                        },
                        new
                        {
                            StudentId = 30,
                            Address = "420 Lê Duẩn, Phường 3, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lyduchung@gmail.com",
                            FullName = "Lý Đức Hùng",
                            Gender = "Nam",
                            Phone = "0979147706",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 41
                        },
                        new
                        {
                            StudentId = 31,
                            Address = "313 Nguyễn Trãi, Phường 1, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phanhoangviet@gmail.com",
                            FullName = "Phan Hoàng Việt",
                            Gender = "Nam",
                            Phone = "0948096887",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 42
                        },
                        new
                        {
                            StudentId = 32,
                            Address = "92 Nam Kỳ Khởi Nghĩa, Phường 3, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "duongvietgiang@gmail.com",
                            FullName = "Dương Việt Giang",
                            Gender = "Nam",
                            Phone = "0908999183",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 43
                        },
                        new
                        {
                            StudentId = 33,
                            Address = "439 Điện Biên Phủ, Phường 10, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ngoduckien@gmail.com",
                            FullName = "Ngô Đức Kiên",
                            Gender = "Nam",
                            Phone = "0915130808",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 44
                        },
                        new
                        {
                            StudentId = 34,
                            Address = "670 Hai Bà Trưng, Phường 8, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2004, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hoanghongtrinh@gmail.com",
                            FullName = "Hoàng Hồng Trinh",
                            Gender = "Nữ",
                            Phone = "0935456272",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 45
                        },
                        new
                        {
                            StudentId = 35,
                            Address = "145 Hai Bà Trưng, Phường 15, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2001, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenanhphuc@gmail.com",
                            FullName = "Nguyễn Anh Phúc",
                            Gender = "Nam",
                            Phone = "0912229110",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 46
                        },
                        new
                        {
                            StudentId = 36,
                            Address = "577 Hai Bà Trưng, Phường 15, Bình Thạnh, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 11, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuhoanghung@gmail.com",
                            FullName = "Vũ Hoàng Hùng",
                            Gender = "Nam",
                            Phone = "0986075395",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 47
                        },
                        new
                        {
                            StudentId = 37,
                            Address = "225 Điện Biên Phủ, Phường 6, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2002, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lehoanghai@gmail.com",
                            FullName = "Lê Hoàng Hải",
                            Gender = "Nam",
                            Phone = "0913607983",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 48
                        },
                        new
                        {
                            StudentId = 38,
                            Address = "13 Hai Bà Trưng, Phường 13, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2004, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "buiphuonghanh@gmail.com",
                            FullName = "Bùi Phương Hạnh",
                            Gender = "Nữ",
                            Phone = "0902548511",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 49
                        },
                        new
                        {
                            StudentId = 39,
                            Address = "935 Nguyễn Trãi, Phường 9, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1999, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lephuongdung@gmail.com",
                            FullName = "Lê Phương Dung",
                            Gender = "Nữ",
                            Phone = "0971162230",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 50
                        },
                        new
                        {
                            StudentId = 40,
                            Address = "930 Nam Kỳ Khởi Nghĩa, Phường 14, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dangquynhlinh@gmail.com",
                            FullName = "Đặng Quỳnh Linh",
                            Gender = "Nữ",
                            Phone = "0973138181",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 51
                        },
                        new
                        {
                            StudentId = 41,
                            Address = "176 Nam Kỳ Khởi Nghĩa, Phường 13, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamhongvy@gmail.com",
                            FullName = "Phạm Hồng Vy",
                            Gender = "Nữ",
                            Phone = "0967817881",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 52
                        },
                        new
                        {
                            StudentId = 42,
                            Address = "728 Lê Duẩn, Phường 7, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2002, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenthutrinh@gmail.com",
                            FullName = "Nguyễn Thu Trinh",
                            Gender = "Nữ",
                            Phone = "0975163555",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 53
                        },
                        new
                        {
                            StudentId = 43,
                            Address = "685 Nguyễn Trãi, Phường 7, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2001, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamhonghoa@gmail.com",
                            FullName = "Phạm Hồng Hoa",
                            Gender = "Nữ",
                            Phone = "0966120253",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 54
                        },
                        new
                        {
                            StudentId = 44,
                            Address = "908 Hai Bà Trưng, Phường 3, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2003, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "trankimlan@gmail.com",
                            FullName = "Trần Kim Lan",
                            Gender = "Nữ",
                            Phone = "0979996207",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 55
                        },
                        new
                        {
                            StudentId = 45,
                            Address = "533 Lê Duẩn, Phường 7, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2003, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenngocbich@gmail.com",
                            FullName = "Nguyễn Ngọc Bích",
                            Gender = "Nữ",
                            Phone = "0976799667",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 56
                        },
                        new
                        {
                            StudentId = 46,
                            Address = "81 Điện Biên Phủ, Phường 15, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2001, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hoangvannam@gmail.com",
                            FullName = "Hoàng Văn Nam",
                            Gender = "Nam",
                            Phone = "0909722815",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 57
                        },
                        new
                        {
                            StudentId = 47,
                            Address = "312 Cách Mạng Tháng 8, Phường 3, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2003, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ngongocquynh@gmail.com",
                            FullName = "Ngô Ngọc Quỳnh",
                            Gender = "Nữ",
                            Phone = "0947851696",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 58
                        },
                        new
                        {
                            StudentId = 48,
                            Address = "225 Trần Hưng Đạo, Phường 13, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ngokhanhtrang@gmail.com",
                            FullName = "Ngô Khánh Trang",
                            Gender = "Nữ",
                            Phone = "0947812810",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 59
                        },
                        new
                        {
                            StudentId = 49,
                            Address = "684 Lê Duẩn, Phường 5, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dophuonghoa@gmail.com",
                            FullName = "Đỗ Phương Hoa",
                            Gender = "Nữ",
                            Phone = "0939576076",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 60
                        },
                        new
                        {
                            StudentId = 50,
                            Address = "260 Trần Hưng Đạo, Phường 10, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranhongquynh@gmail.com",
                            FullName = "Trần Hồng Quỳnh",
                            Gender = "Nữ",
                            Phone = "0934340845",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 61
                        },
                        new
                        {
                            StudentId = 51,
                            Address = "681 Điện Biên Phủ, Phường 1, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2004, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phanthanhthao@gmail.com",
                            FullName = "Phan Thanh Thảo",
                            Gender = "Nữ",
                            Phone = "0979294272",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 62
                        },
                        new
                        {
                            StudentId = 52,
                            Address = "146 Nam Kỳ Khởi Nghĩa, Phường 8, Bình Thạnh, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2001, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamthutuyet@gmail.com",
                            FullName = "Phạm Thu Tuyết",
                            Gender = "Nữ",
                            Phone = "0981842524",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 63
                        },
                        new
                        {
                            StudentId = 53,
                            Address = "496 Trần Hưng Đạo, Phường 5, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 12, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lyphuongbich@gmail.com",
                            FullName = "Lý Phương Bích",
                            Gender = "Nữ",
                            Phone = "0978481188",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 64
                        },
                        new
                        {
                            StudentId = 54,
                            Address = "302 Nguyễn Trãi, Phường 5, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lyquynhngoc@gmail.com",
                            FullName = "Lý Quỳnh Ngọc",
                            Gender = "Nữ",
                            Phone = "0935606980",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 65
                        },
                        new
                        {
                            StudentId = 55,
                            Address = "733 Nguyễn Trãi, Phường 2, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2004, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "buingoclinh@gmail.com",
                            FullName = "Bùi Ngọc Linh",
                            Gender = "Nữ",
                            Phone = "0924879923",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 66
                        },
                        new
                        {
                            StudentId = 56,
                            Address = "936 Nam Kỳ Khởi Nghĩa, Phường 10, Bình Thạnh, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2001, 7, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuquynhhoa@gmail.com",
                            FullName = "Vũ Quỳnh Hoa",
                            Gender = "Nữ",
                            Phone = "0972044645",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 67
                        },
                        new
                        {
                            StudentId = 57,
                            Address = "409 Nam Kỳ Khởi Nghĩa, Phường 15, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2003, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lyngockien@gmail.com",
                            FullName = "Lý Ngọc Kiên",
                            Gender = "Nam",
                            Phone = "0981098919",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 68
                        },
                        new
                        {
                            StudentId = 58,
                            Address = "694 Điện Biên Phủ, Phường 13, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doducdat@gmail.com",
                            FullName = "Đỗ Đức Đạt",
                            Gender = "Nam",
                            Phone = "0979147720",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 69
                        },
                        new
                        {
                            StudentId = 59,
                            Address = "448 Nguyễn Trãi, Phường 14, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 2, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doquocphuc@gmail.com",
                            FullName = "Đỗ Quốc Phúc",
                            Gender = "Nam",
                            Phone = "0907610562",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 70
                        },
                        new
                        {
                            StudentId = 60,
                            Address = "789 Trần Hưng Đạo, Phường 5, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenhoangkien@gmail.com",
                            FullName = "Nguyễn Hoàng Kiên",
                            Gender = "Nam",
                            Phone = "0964551070",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 71
                        },
                        new
                        {
                            StudentId = 61,
                            Address = "809 Điện Biên Phủ, Phường 1, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2001, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranphuongmai@gmail.com",
                            FullName = "Trần Phương Mai",
                            Gender = "Nữ",
                            Phone = "0906871360",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 72
                        },
                        new
                        {
                            StudentId = 62,
                            Address = "127 Cách Mạng Tháng 8, Phường 4, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamvanphuc@gmail.com",
                            FullName = "Phạm Văn Phúc",
                            Gender = "Nam",
                            Phone = "0925002120",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 73
                        },
                        new
                        {
                            StudentId = 63,
                            Address = "36 Hai Bà Trưng, Phường 10, Bình Thạnh, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2002, 2, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lytructrang@gmail.com",
                            FullName = "Lý Trúc Trang",
                            Gender = "Nữ",
                            Phone = "0913747534",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 74
                        },
                        new
                        {
                            StudentId = 64,
                            Address = "834 Lê Duẩn, Phường 13, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2002, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phanhongphuong@gmail.com",
                            FullName = "Phan Hồng Phương",
                            Gender = "Nữ",
                            Phone = "0932709620",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 75
                        },
                        new
                        {
                            StudentId = 65,
                            Address = "440 Nam Kỳ Khởi Nghĩa, Phường 8, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2003, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuthanhnam@gmail.com",
                            FullName = "Vũ Thành Nam",
                            Gender = "Nam",
                            Phone = "0962156902",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 76
                        },
                        new
                        {
                            StudentId = 66,
                            Address = "951 Cách Mạng Tháng 8, Phường 13, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2002, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuphuonglinh@gmail.com",
                            FullName = "Vũ Phương Linh",
                            Gender = "Nữ",
                            Phone = "0973955087",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 77
                        },
                        new
                        {
                            StudentId = 67,
                            Address = "259 Nam Kỳ Khởi Nghĩa, Phường 8, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1999, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phanthanhhanh@gmail.com",
                            FullName = "Phan Thanh Hạnh",
                            Gender = "Nữ",
                            Phone = "0965118725",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 78
                        },
                        new
                        {
                            StudentId = 68,
                            Address = "826 Hai Bà Trưng, Phường 6, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuthingoc@gmail.com",
                            FullName = "Vũ Thị Ngọc",
                            Gender = "Nữ",
                            Phone = "0964050766",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 79
                        },
                        new
                        {
                            StudentId = 69,
                            Address = "510 Cách Mạng Tháng 8, Phường 13, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2001, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "buithituyet@gmail.com",
                            FullName = "Bùi Thị Tuyết",
                            Gender = "Nữ",
                            Phone = "0932436347",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 80
                        },
                        new
                        {
                            StudentId = 70,
                            Address = "718 Nguyễn Trãi, Phường 5, Bình Thạnh, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2002, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ngophuonghoa@gmail.com",
                            FullName = "Ngô Phương Hoa",
                            Gender = "Nữ",
                            Phone = "0902561176",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 81
                        },
                        new
                        {
                            StudentId = 71,
                            Address = "474 Hai Bà Trưng, Phường 5, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2003, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doquynhtuyet@gmail.com",
                            FullName = "Đỗ Quỳnh Tuyết",
                            Gender = "Nữ",
                            Phone = "0968138769",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 82
                        },
                        new
                        {
                            StudentId = 72,
                            Address = "766 Trần Hưng Đạo, Phường 5, Bình Thạnh, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranducphong@gmail.com",
                            FullName = "Trần Đức Phong",
                            Gender = "Nam",
                            Phone = "0919990305",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 83
                        },
                        new
                        {
                            StudentId = 73,
                            Address = "735 Cách Mạng Tháng 8, Phường 3, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranhongquynh1@gmail.com",
                            FullName = "Trần Hồng Quỳnh",
                            Gender = "Nữ",
                            Phone = "0937054579",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 84
                        },
                        new
                        {
                            StudentId = 74,
                            Address = "301 Trần Hưng Đạo, Phường 8, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1999, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenthanhtung@gmail.com",
                            FullName = "Nguyễn Thành Tùng",
                            Gender = "Nam",
                            Phone = "0929235577",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 85
                        },
                        new
                        {
                            StudentId = 75,
                            Address = "85 Cách Mạng Tháng 8, Phường 11, Bình Thạnh, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1999, 7, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lethihanh@gmail.com",
                            FullName = "Lê Thị Hạnh",
                            Gender = "Nữ",
                            Phone = "0982914064",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 86
                        },
                        new
                        {
                            StudentId = 76,
                            Address = "792 Trần Hưng Đạo, Phường 10, Tân Bình, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2001, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lequocbach@gmail.com",
                            FullName = "Lê Quốc Bách",
                            Gender = "Nam",
                            Phone = "0942429098",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 87
                        },
                        new
                        {
                            StudentId = 77,
                            Address = "322 Cách Mạng Tháng 8, Phường 10, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2002, 10, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lythanhkien@gmail.com",
                            FullName = "Lý Thành Kiên",
                            Gender = "Nam",
                            Phone = "0988427625",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 88
                        },
                        new
                        {
                            StudentId = 78,
                            Address = "187 Cách Mạng Tháng 8, Phường 2, Q3, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1999, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lyducthinh@gmail.com",
                            FullName = "Lý Đức Thịnh",
                            Gender = "Nam",
                            Phone = "0935440025",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 89
                        },
                        new
                        {
                            StudentId = 79,
                            Address = "733 Hai Bà Trưng, Phường 12, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phananhphuc@gmail.com",
                            FullName = "Phan Anh Phúc",
                            Gender = "Nam",
                            Phone = "0985886520",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 90
                        },
                        new
                        {
                            StudentId = 80,
                            Address = "673 Nguyễn Trãi, Phường 15, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1999, 9, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ngoducdat@gmail.com",
                            FullName = "Ngô Đức Đạt",
                            Gender = "Nam",
                            Phone = "0938132648",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 91
                        },
                        new
                        {
                            StudentId = 81,
                            Address = "715 Hai Bà Trưng, Phường 12, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranvanhung@gmail.com",
                            FullName = "Trần Văn Hùng",
                            Gender = "Nam",
                            Phone = "0945842082",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 92
                        },
                        new
                        {
                            StudentId = 82,
                            Address = "340 Cách Mạng Tháng 8, Phường 5, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "buiquynhngoc@gmail.com",
                            FullName = "Bùi Quỳnh Ngọc",
                            Gender = "Nữ",
                            Phone = "0982349590",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 93
                        },
                        new
                        {
                            StudentId = 83,
                            Address = "541 Điện Biên Phủ, Phường 8, Q5, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 3, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamngocbach@gmail.com",
                            FullName = "Phạm Ngọc Bách",
                            Gender = "Nam",
                            Phone = "0905521644",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 94
                        },
                        new
                        {
                            StudentId = 84,
                            Address = "351 Hai Bà Trưng, Phường 11, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "danghuuthinh@gmail.com",
                            FullName = "Đặng Hữu Thịnh",
                            Gender = "Nam",
                            Phone = "0982530793",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 95
                        },
                        new
                        {
                            StudentId = 85,
                            Address = "332 Hai Bà Trưng, Phường 6, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 8, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuhuutuan@gmail.com",
                            FullName = "Vũ Hữu Tuấn",
                            Gender = "Nam",
                            Phone = "0947718473",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 96
                        },
                        new
                        {
                            StudentId = 86,
                            Address = "380 Cách Mạng Tháng 8, Phường 13, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "buithidung@gmail.com",
                            FullName = "Bùi Thị Dung",
                            Gender = "Nữ",
                            Phone = "0987933143",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 97
                        },
                        new
                        {
                            StudentId = 87,
                            Address = "506 Lê Duẩn, Phường 1, Bình Thạnh, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2002, 8, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lythithao@gmail.com",
                            FullName = "Lý Thị Thảo",
                            Gender = "Nữ",
                            Phone = "0943198037",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 98
                        },
                        new
                        {
                            StudentId = 88,
                            Address = "944 Lê Duẩn, Phường 8, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1999, 4, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "duongquoctung@gmail.com",
                            FullName = "Dương Quốc Tùng",
                            Gender = "Nam",
                            Phone = "0907844947",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 99
                        },
                        new
                        {
                            StudentId = 89,
                            Address = "477 Cách Mạng Tháng 8, Phường 3, Q10, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2005, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dohoanghuy@gmail.com",
                            FullName = "Đỗ Hoàng Huy",
                            Gender = "Nam",
                            Phone = "0947970771",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 100
                        },
                        new
                        {
                            StudentId = 90,
                            Address = "529 Hai Bà Trưng, Phường 14, Q1, TP.HCM",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2004, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dangthanhquan@gmail.com",
                            FullName = "Đặng Thành Quân",
                            Gender = "Nam",
                            Phone = "0915634662",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 101
                        });
                });

            modelBuilder.Entity("StudentService.Models.StudentCredit", b =>
                {
                    b.Property<int>("CreditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CreditId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SourceClassId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("CreditId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCredits");
                });

            modelBuilder.Entity("StudentService.Models.SupportMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FromClassId")
                        .HasColumnType("int");

                    b.Property<string>("FromClassName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("ToClassId")
                        .HasColumnType("int");

                    b.Property<string>("ToClassName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("SupportMessages");
                });

            modelBuilder.Entity("StudentService.Models.Attendance", b =>
                {
                    b.HasOne("StudentService.Models.Enrollment", "Enrollment")
                        .WithMany("Attendances")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("StudentService.Models.CourseQueue", b =>
                {
                    b.HasOne("StudentService.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentService.Models.Enrollment", b =>
                {
                    b.HasOne("StudentService.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentService.Models.ExamResult", b =>
                {
                    b.HasOne("StudentService.Models.Enrollment", "Enrollment")
                        .WithMany("ExamResults")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("StudentService.Models.StudentCredit", b =>
                {
                    b.HasOne("StudentService.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentService.Models.SupportMessage", b =>
                {
                    b.HasOne("StudentService.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentService.Models.Enrollment", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ExamResults");
                });

            modelBuilder.Entity("StudentService.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
