// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentService.Data;

#nullable disable

namespace PaymentService.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260605065918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaymentService.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("Status");

                    b.HasIndex("StudentUserId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            ClassId = 1,
                            CreatedAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 2500000m,
                            RemainingAmount = 0m,
                            Status = "HoanTat",
                            StudentUserId = 5,
                            TotalAmount = 2500000m,
                            UpdatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PaymentId = 2,
                            ClassId = 1,
                            CreatedAt = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 1500000m,
                            RemainingAmount = 1000000m,
                            Status = "DangTT",
                            StudentUserId = 6,
                            TotalAmount = 2500000m,
                            UpdatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PaymentId = 3,
                            ClassId = 3,
                            CreatedAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 0m,
                            RemainingAmount = 3500000m,
                            Status = "ChuaTT",
                            StudentUserId = 7,
                            TotalAmount = 3500000m,
                            UpdatedAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PaymentId = 4,
                            ClassId = 4,
                            CreatedAt = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAmount = 3000000m,
                            RemainingAmount = 0m,
                            Status = "HoanTat",
                            StudentUserId = 5,
                            TotalAmount = 3000000m,
                            UpdatedAt = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PaymentService.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ReceivedByUserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentTransactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Amount = 2500000m,
                            Note = "Thanh toán đầy đủ",
                            PaidAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentId = 1,
                            PaymentMethod = "ChuyenKhoan",
                            ReceivedByUserId = 1
                        },
                        new
                        {
                            TransactionId = 2,
                            Amount = 1000000m,
                            Note = "Đợt 1",
                            PaidAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentId = 2,
                            PaymentMethod = "TienMat",
                            ReceivedByUserId = 1
                        },
                        new
                        {
                            TransactionId = 3,
                            Amount = 500000m,
                            Note = "Đợt 2",
                            PaidAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentId = 2,
                            PaymentMethod = "ChuyenKhoan",
                            ReceivedByUserId = 1
                        },
                        new
                        {
                            TransactionId = 4,
                            Amount = 3000000m,
                            Note = "Thanh toán đầy đủ bằng thẻ",
                            PaidAt = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentId = 4,
                            PaymentMethod = "TheTD",
                            ReceivedByUserId = 1
                        });
                });

            modelBuilder.Entity("PaymentService.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Role");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@trainingcenter.vn",
                            FullName = "Quản trị viên",
                            IsActive = true,
                            PasswordHash = "$2a$11$7wHWG7dZnyt5WV1Gwe6PK.weH5mleI3aSegpTfqGNr5UdMvha6URC",
                            Phone = "0901000001",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenvana@trainingcenter.vn",
                            FullName = "Nguyễn Văn A",
                            IsActive = true,
                            PasswordHash = "$2a$11$hjgbS3EJUerHIvpo7pRUnu9OHI3aGgqwJn/vypDh18juRtuUj3fI2",
                            Phone = "0901000002",
                            Role = "GiaoVien",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "nguyenvana"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranthib@trainingcenter.vn",
                            FullName = "Trần Thị B",
                            IsActive = true,
                            PasswordHash = "$2a$11$a65jsmNide60EpGGVc1Ft.THLyYl73hO5blSL/YEvUaOVROiZL8Dq",
                            Phone = "0901000003",
                            Role = "GiaoVien",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "tranthib"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "levanc@trainingcenter.vn",
                            FullName = "Lê Văn C",
                            IsActive = true,
                            PasswordHash = "$2a$11$w9aGuf8EgEOtvtmTk8EO9OM.m8g9ZyusZo1u5bP/L0c3/EprYXGAm",
                            Phone = "0901000004",
                            Role = "GiaoVien",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "levanc"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamvand@gmail.com",
                            FullName = "Phạm Văn D",
                            IsActive = true,
                            PasswordHash = "$2a$11$vOY3o7J6ZuVj1k34/Ne7me.cbXdSO11UfXzIdGkBXU0eSa9RkoFSS",
                            Phone = "0901000005",
                            Role = "HocVien",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "phamvand"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hoangthie@gmail.com",
                            FullName = "Hoàng Thị E",
                            IsActive = true,
                            PasswordHash = "$2a$11$CxLT8mClksX6DaIqPY/o0eElofHwX7w3diDw4PPnzdEg.CGYfcaTq",
                            Phone = "0901000006",
                            Role = "HocVien",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "hoangthie"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vuvang@gmail.com",
                            FullName = "Vũ Văn G",
                            IsActive = true,
                            PasswordHash = "$2a$11$AqFRtTKVmDdo8gO9Fxb6LuNagQk1Cg74vqA1gjFft4VWo4/bkApdW",
                            Phone = "0901000007",
                            Role = "HocVien",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "vuvang"
                        });
                });

            modelBuilder.Entity("PaymentService.Models.Payment", b =>
                {
                    b.HasOne("PaymentService.Models.User", "StudentUser")
                        .WithMany("Payments")
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudentUser");
                });

            modelBuilder.Entity("PaymentService.Models.PaymentTransaction", b =>
                {
                    b.HasOne("PaymentService.Models.Payment", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("PaymentService.Models.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PaymentService.Models.User", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
